apiVersion: v1
kind: Service
metadata:
  name: App1-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: App1
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30021
---
apiVersion: v1
kind: Service
metadata:
  name: App2-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: App2
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30022
---
apiVersion: v1
kind: Service
metadata:
  name: App3-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: App3
  ports:
  - port: 8090
    targetPort: 8090
    nodePort: 30023
---
