package Mining.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Work extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Work() {
    super(0x222ccd66f9d64014L, 0x8569354bddee8138L, 0x5d25b8d4c26819e4L, "Work", "r:589c5fd8-b628-4aae-9e87-31a99b5068a7(Mining.structure)/6711974043599772132");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Development_0 = new EnumerationDescriptor.MemberDescriptor("Development", "Development", 0x5d25b8d4c26819e5L, "r:589c5fd8-b628-4aae-9e87-31a99b5068a7(Mining.structure)/6711974043599772133");
  private final EnumerationDescriptor.MemberDescriptor myMember_Exploitation_0 = new EnumerationDescriptor.MemberDescriptor("Exploitation", "Exploitation", 0x5d25b8d4c26819e6L, "r:589c5fd8-b628-4aae-9e87-31a99b5068a7(Mining.structure)/6711974043599772134");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x222ccd66f9d64014L, 0x8569354bddee8138L, 0x5d25b8d4c26819e4L, 0x5d25b8d4c26819e5L, 0x5d25b8d4c26819e6L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Development_0, myMember_Exploitation_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Development":
        return myMember_Development_0;
      case "Exploitation":
        return myMember_Exploitation_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
