apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  prometheus.rules: |-
    groups:
    - name: Alert-Alarm
      interval: 1s
      rules:
      - alert: Alarm
        # Condition for alerting
        expr: room_ch4 > 3
        for: 5s
        annotations:
          adaptations: '{"operate_actuator_0.5936407199795086":{"broker_ip":"192.168.10.10","port":30023,"topic":"room/alarm","message":"on"}}'
        labels:
          severity: 'critical'
          actions: 'all'

    - name: Alert-Offloading App
      interval: 1s
      rules:
      - alert: Offloading App
        # Condition for alerting
        expr: 100 - (avg by(node_hostname) (rate(node_cpu_seconds_total{mode="idle",node_hostname="edge_01"}[30s])) * 100) > 80
        for: 1m
        annotations:
          adaptations: '{"offloading_0.975092548967118":{"pod_name":"C_2","image":"iot-system/app2","namespace":"default","requirements":{"memory":"700M","cpu":"300m"},"volumes":[],"hosts":{"node":{"operator":"In","values":["fog_01"]},"region":{"operator":"In","values":["Example Mine"]},"cluster":{"operator":"In","values":[]}}}}'
        labels:
          severity: 'critical'
          actions: 'all'
